---
- name: Install containerd on CentOS 8
  hosts: ansible_targets
  become: true
  tasks:
    - name: Reset problematic Perl modules (fixes modularity conflicts)
      ansible.builtin.shell: |
        dnf module reset perl-IO-Socket-SSL perl-libwww-perl perl-DBI perl-DBD-MySQL perl-DBD-SQLite -y
      args:
        warn: false
        
    - name: Install required packages
      dnf:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present

    - name: Add Docker repository
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo

    - name: Install containerd
      dnf:
        name: containerd.io-1.6.20-3.1.el8
        state: present

    - name: Enable and start containerd
      systemd:
        name: containerd
        enabled: yes
        state: started
