---
- name: Install containerd on CentOS 8
  hosts: ansible_targets
  become: true
  tasks:
    - name: Remove conflicting container packages
      ansible.builtin.dnf:
        name:
          - podman
          - runc
          - docker-ce
          - docker-ce-cli
          - containerd
          - containerd.io
        state: absent
      ignore_errors: true

    - name: Reset container-tools module
      ansible.builtin.shell: dnf -y module reset container-tools

    - name: Enable container-tools module (version 4.0)
      ansible.builtin.shell: dnf -y module enable container-tools:4.0

    - name: Clean DNF metadata
      ansible.builtin.shell: dnf clean all

    - name: Make DNF cache
      ansible.builtin.shell: dnf makecache

    - name: Reset problematic Perl modules (fixes modularity conflicts)
      ansible.builtin.shell: |
        dnf module reset perl-IO-Socket-SSL perl-libwww-perl perl-DBI perl-DBD-MySQL perl-DBD-SQLite -y

    - name: Install required packages
      ansible.builtin.dnf:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present

    - name: Add Docker repository
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo

    - name: Install containerd
      ansible.builtin.dnf:
        name: containerd.io-1.6.20-3.1.el8
        state: present

    - name: Enable and start containerd
      ansible.builtin.systemd:
        name: containerd
        enabled: yes
        state: started

    - name: Install Docker Engine
      ansible.builtin.dnf:
        name:
         - docker-ce
         - docker-ce-cli
         - containerd.io
        state: present
 
    - name: Enable and start Docker
      ansible.builtin.systemd:
        name: docker
        enabled: yes
        state: started
